=== deu-coders/burger-xml/burgers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="burger">
        <xsd:annotation>
            <xsd:documentation>
                햄버거의 정보를 나타내는 element이며 버거의 이름, 회사, 설명, 썸네일, 종류(단품/세트) 및 가격, 영양정보 등의 정보가 표시됨.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string" />
                <xsd:element name="company" type="xsd:string" />
                <xsd:element name="description" type="xsd:string" />
                <xsd:element name="thumbnail" type="xsd:anyURI" />
                <xsd:element name="variants">
                    <xsd:complexType>
                        <xsd:choice minOccurs="1" maxOccurs="unbounded">
                            <xsd:element name="variant">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="price" type="xsd:positiveInteger" />
                                    </xsd:sequence>
                                    <xsd:attribute name="name" type="xsd:string" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="nutrition-facts">
                    <xsd:annotation>
                        <xsd:documentation>
                            햄버거의 영양정보를 나타내는 element이다.
                            중량, 칼로리, 당, 단백질, 나트륨, 포화지방 정보를 가지고 있으며 공식 홈페이지에서 제공되는 데이터를 가져왔다.
                        </xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="weight" type="xsd:decimal" />
                            <xsd:element name="calories" type="xsd:decimal" />
                            <xsd:element name="sugars" type="xsd:decimal" />
                            <xsd:element name="protein" type="xsd:decimal" />
                            <xsd:element name="sodium" type="xsd:decimal" />
                            <xsd:element name="saturated-fat" type="xsd:decimal" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="burgers">
        <xsd:complexType>
            <xsd:choice minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="burger" />
            </xsd:choice>
        </xsd:complexType>

        <xsd:unique name="burgerID">
            <xsd:selector xpath="burger" />
            <xsd:field xpath="@id" />
        </xsd:unique>
    </xsd:element>
</xsd:schema>

=== deu-coders/burger-xml/burger.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="burger.xsl" type="text/xsl"?>

<burger
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="burgers.xsd"
>
    <name>빅맥</name>
    <company>맥도날드</company>
    <description>
        100% 순 쇠고기 패티 두 장에 빅맥®만의 특별한 소스.
        입안에서 살살 녹는 치즈와 신선한 양상추, 양파, 그리고 피클까지.
        50년 넘게 전 세계인의 입맛을 사로 잡은 버거의 대명사.
    </description>
    <thumbnail>맥도날드/빅맥.png</thumbnail>
    <variants>
        <variant name="단품">
            <price>4600</price>
        </variant>
        <variant name="세트">
            <price>5900</price>
        </variant>
    </variants>
    <nutrition-facts>
        <weight>223</weight>
        <calories>512</calories>
        <sugars>7</sugars>
        <protein>27</protein>
        <sodium>892</sodium>
        <saturated-fat>11</saturated-fat>
    </nutrition-facts>
</burger>
