=== deu-coders/burger-xml/company.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="company">
        <xsd:annotation>
            <xsd:documentation>
                햄버거를 제조하는 회사에 대한 정보를 나타냄
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="country" type="xsd:string" />
                <xsd:element name="founding-date" type="xsd:date" />
                <xsd:element name="ceo" type="xsd:string" />
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="companies">
        <xsd:complexType>
            <xsd:choice minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="company" />
            </xsd:choice>
        </xsd:complexType>

        <xsd:unique name="companyName">
            <xsd:selector xpath="company" />
            <xsd:field xpath="@name" />
        </xsd:unique>
    </xsd:element>
</xsd:schema>

=== deu-coders/burger-xml/company.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="company.xsl" type="text/xsl"?>

<companies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="company.xsd">
    <company name="맥도날드">
        <country>미국</country>
        <founding-date>1940-05-15</founding-date>
        <ceo>크리스 캠친스키</ceo>
    </company>
    <company name="버거킹">
        <country>미국</country>
        <founding-date>1954-12-04</founding-date>
        <ceo>대니얼 S. 슈워츠</ceo>
    </company>
    <company name="롯데리아">
        <country>일본</country>
        <founding-date>1972-02-02</founding-date>
        <ceo>차우철</ceo>
    </company>
    <company name="맘스터치">
        <country>한국</country>
        <founding-date>2004-02-04</founding-date>
        <ceo>김동전</ceo>
    </company>
</companies>
